# Copyright (C) 2011-2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/pantech/ef63l/extract-files.sh

PRODUCT_COPY_FILES += \
        vendor/pantech/ef63l/proprietary/bin/adsprpcd:/system/bin/adsprpcd \
		vendor/pantech/ef63l/proprietary/etc/sensor_def_qcomdev.conf:/system/etc/sensor_def_qcomdev.conf \
		vendor/pantech/ef63l/proprietary/framework/qcrilhook.jar:/system/framework/qcrilhook.jar \
        vendor/pantech/ef63l/proprietary/lib/libwcnss_qmi.so:/system/lib/libwcnss_qmi.so \
		vendor/pantech/ef63l/proprietary/vendor/lib/libacdbloader.so:/system/vendor/lib/libacdbloader.so 

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/pantech/ef63l/proprietary/app,system/app)
PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/pantech/ef63l/proprietary/bin,system/bin)
PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/pantech/ef63l/proprietary/lib,system/lib)
PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/pantech/ef63l/proprietary/etc,system/etc)
PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/pantech/ef63l/proprietary/priv-app,system/priv-app)
PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/pantech/ef63l/proprietary/framework,system/framework)
PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/pantech/ef63l/proprietary/vendor,system/vendor)

